services:
  protobuf:
    build:
      context: .
      dockerfile: tools/protobuf/Dockerfile
    container_name: hft-protobuf
    working_dir: /workspace
    volumes:
      - ./:/workspace
    profiles:
      - tools
    networks:
      - hft-network

  redis:
    image: redis:7-alpine
    container_name: hft-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - hft-network

  nats:
    image: nats:2.12.4-alpine
    container_name: hft-nats
    command:
      - "-c"
      - "/etc/nats/nats.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
      - ./tools/nats/nats.conf:/etc/nats/nats.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8222/healthz | grep -q ok"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - hft-network

  postgresql:
    build: ./tools/postgre
    container_name: hft-postgresql
    environment:
      POSTGRES_DB: hft
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=hft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d hft"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    networks:
      - hft-network
volumes:
  redis_data:
  nats_data:
  postgres_data:

networks:
  hft-network:
    driver: bridge
