// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/order_engine/order_engine.proto

package order_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderEngineService_PlaceOrder_FullMethodName = "/pb.order_engine.OrderEngineService/PlaceOrder"
)

// OrderEngineServiceClient is the client API for OrderEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderEngineServiceClient interface {
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
}

type orderEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEngineServiceClient(cc grpc.ClientConnInterface) OrderEngineServiceClient {
	return &orderEngineServiceClient{cc}
}

func (c *orderEngineServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, OrderEngineService_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderEngineServiceServer is the server API for OrderEngineService service.
// All implementations must embed UnimplementedOrderEngineServiceServer
// for forward compatibility.
type OrderEngineServiceServer interface {
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	mustEmbedUnimplementedOrderEngineServiceServer()
}

// UnimplementedOrderEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderEngineServiceServer struct{}

func (UnimplementedOrderEngineServiceServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedOrderEngineServiceServer) mustEmbedUnimplementedOrderEngineServiceServer() {}
func (UnimplementedOrderEngineServiceServer) testEmbeddedByValue()                            {}

// UnsafeOrderEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEngineServiceServer will
// result in compilation errors.
type UnsafeOrderEngineServiceServer interface {
	mustEmbedUnimplementedOrderEngineServiceServer()
}

func RegisterOrderEngineServiceServer(s grpc.ServiceRegistrar, srv OrderEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderEngineService_ServiceDesc, srv)
}

func _OrderEngineService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEngineServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEngineService_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEngineServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderEngineService_ServiceDesc is the grpc.ServiceDesc for OrderEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order_engine.OrderEngineService",
	HandlerType: (*OrderEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _OrderEngineService_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/order_engine/order_engine.proto",
}
