// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/order_engine/order_engine.proto

package order_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_order_engine_order_engine_proto protoreflect.FileDescriptor

const file_pb_order_engine_order_engine_proto_rawDesc = "" +
	"\n" +
	"\"pb/order_engine/order_engine.proto\x12\x0fpb.order_engine\x1a\x1bpb/order_engine/order.proto2k\n" +
	"\x12OrderEngineService\x12U\n" +
	"\n" +
	"PlaceOrder\x12\".pb.order_engine.PlaceOrderRequest\x1a#.pb.order_engine.PlaceOrderResponseB\x11Z\x0fpb/order_engineb\x06proto3"

var file_pb_order_engine_order_engine_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),  // 0: pb.order_engine.PlaceOrderRequest
	(*PlaceOrderResponse)(nil), // 1: pb.order_engine.PlaceOrderResponse
}
var file_pb_order_engine_order_engine_proto_depIdxs = []int32{
	0, // 0: pb.order_engine.OrderEngineService.PlaceOrder:input_type -> pb.order_engine.PlaceOrderRequest
	1, // 1: pb.order_engine.OrderEngineService.PlaceOrder:output_type -> pb.order_engine.PlaceOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_order_engine_order_engine_proto_init() }
func file_pb_order_engine_order_engine_proto_init() {
	if File_pb_order_engine_order_engine_proto != nil {
		return
	}
	file_pb_order_engine_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_order_engine_order_engine_proto_rawDesc), len(file_pb_order_engine_order_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_order_engine_order_engine_proto_goTypes,
		DependencyIndexes: file_pb_order_engine_order_engine_proto_depIdxs,
	}.Build()
	File_pb_order_engine_order_engine_proto = out.File
	file_pb_order_engine_order_engine_proto_goTypes = nil
	file_pb_order_engine_order_engine_proto_depIdxs = nil
}
