// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/order_engine/order.proto

package order_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId        *string                `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	Exchange       string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol         string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Side           string                 `protobuf:"bytes,7,opt,name=side,proto3" json:"side,omitempty"`
	Price          string                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       string                 `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RequestedAt    int64                  `protobuf:"varint,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	ExpiredAt      *int64                 `protobuf:"varint,11,opt,name=expired_at,json=expiredAt,proto3,oneof" json:"expired_at,omitempty"`
	Source         string                 `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	StrategyId     *string                `protobuf:"bytes,13,opt,name=strategy_id,json=strategyId,proto3,oneof" json:"strategy_id,omitempty"`
	IsPaperTrading bool                   `protobuf:"varint,14,opt,name=is_paper_trading,json=isPaperTrading,proto3" json:"is_paper_trading,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_pb_order_engine_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_engine_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_engine_order_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PlaceOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PlaceOrderRequest) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *PlaceOrderRequest) GetExpiredAt() int64 {
	if x != nil && x.ExpiredAt != nil {
		return *x.ExpiredAt
	}
	return 0
}

func (x *PlaceOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PlaceOrderRequest) GetStrategyId() string {
	if x != nil && x.StrategyId != nil {
		return *x.StrategyId
	}
	return ""
}

func (x *PlaceOrderRequest) GetIsPaperTrading() bool {
	if x != nil {
		return x.IsPaperTrading
	}
	return false
}

type PlaceOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange          string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol            string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId           string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId     *string                `protobuf:"bytes,7,opt,name=client_order_id,json=clientOrderId,proto3,oneof" json:"client_order_id,omitempty"`
	Side              string                 `protobuf:"bytes,8,opt,name=side,proto3" json:"side,omitempty"`
	Type              string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Price             *string                `protobuf:"bytes,10,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Quantity          string                 `protobuf:"bytes,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQuantity    string                 `protobuf:"bytes,12,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	AvgFillPrice      *string                `protobuf:"bytes,13,opt,name=avg_fill_price,json=avgFillPrice,proto3,oneof" json:"avg_fill_price,omitempty"`
	Status            string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Leverage          *string                `protobuf:"bytes,15,opt,name=leverage,proto3,oneof" json:"leverage,omitempty"`
	Fee               *string                `protobuf:"bytes,16,opt,name=fee,proto3,oneof" json:"fee,omitempty"`
	RealizedPnl       *string                `protobuf:"bytes,17,opt,name=realized_pnl,json=realizedPnl,proto3,oneof" json:"realized_pnl,omitempty"`
	CreatedAtExchange *int64                 `protobuf:"varint,18,opt,name=created_at_exchange,json=createdAtExchange,proto3,oneof" json:"created_at_exchange,omitempty"`
	SentAt            *int64                 `protobuf:"varint,19,opt,name=sent_at,json=sentAt,proto3,oneof" json:"sent_at,omitempty"`
	AcknowledgedAt    *int64                 `protobuf:"varint,20,opt,name=acknowledged_at,json=acknowledgedAt,proto3,oneof" json:"acknowledged_at,omitempty"`
	FilledAt          *int64                 `protobuf:"varint,21,opt,name=filled_at,json=filledAt,proto3,oneof" json:"filled_at,omitempty"`
	StrategyId        *string                `protobuf:"bytes,22,opt,name=strategy_id,json=strategyId,proto3,oneof" json:"strategy_id,omitempty"`
	ErrorMessage      *string                `protobuf:"bytes,23,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsPaperTrading    bool                   `protobuf:"varint,26,opt,name=is_paper_trading,json=isPaperTrading,proto3" json:"is_paper_trading,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_pb_order_engine_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_engine_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_engine_order_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlaceOrderResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlaceOrderResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PlaceOrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetClientOrderId() string {
	if x != nil && x.ClientOrderId != nil {
		return *x.ClientOrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PlaceOrderResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlaceOrderResponse) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *PlaceOrderResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PlaceOrderResponse) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *PlaceOrderResponse) GetAvgFillPrice() string {
	if x != nil && x.AvgFillPrice != nil {
		return *x.AvgFillPrice
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceOrderResponse) GetLeverage() string {
	if x != nil && x.Leverage != nil {
		return *x.Leverage
	}
	return ""
}

func (x *PlaceOrderResponse) GetFee() string {
	if x != nil && x.Fee != nil {
		return *x.Fee
	}
	return ""
}

func (x *PlaceOrderResponse) GetRealizedPnl() string {
	if x != nil && x.RealizedPnl != nil {
		return *x.RealizedPnl
	}
	return ""
}

func (x *PlaceOrderResponse) GetCreatedAtExchange() int64 {
	if x != nil && x.CreatedAtExchange != nil {
		return *x.CreatedAtExchange
	}
	return 0
}

func (x *PlaceOrderResponse) GetSentAt() int64 {
	if x != nil && x.SentAt != nil {
		return *x.SentAt
	}
	return 0
}

func (x *PlaceOrderResponse) GetAcknowledgedAt() int64 {
	if x != nil && x.AcknowledgedAt != nil {
		return *x.AcknowledgedAt
	}
	return 0
}

func (x *PlaceOrderResponse) GetFilledAt() int64 {
	if x != nil && x.FilledAt != nil {
		return *x.FilledAt
	}
	return 0
}

func (x *PlaceOrderResponse) GetStrategyId() string {
	if x != nil && x.StrategyId != nil {
		return *x.StrategyId
	}
	return ""
}

func (x *PlaceOrderResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *PlaceOrderResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PlaceOrderResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PlaceOrderResponse) GetIsPaperTrading() bool {
	if x != nil {
		return x.IsPaperTrading
	}
	return false
}

var File_pb_order_engine_order_proto protoreflect.FileDescriptor

const file_pb_order_engine_order_proto_rawDesc = "" +
	"\n" +
	"\x1bpb/order_engine/order.proto\x12\x0fpb.order_engine\"\xd4\x03\n" +
	"\x11PlaceOrderRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\border_id\x18\x03 \x01(\tH\x00R\aorderId\x88\x01\x01\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04side\x18\a \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\t \x01(\tR\bquantity\x12!\n" +
	"\frequested_at\x18\n" +
	" \x01(\x03R\vrequestedAt\x12\"\n" +
	"\n" +
	"expired_at\x18\v \x01(\x03H\x01R\texpiredAt\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x12$\n" +
	"\vstrategy_id\x18\r \x01(\tH\x02R\n" +
	"strategyId\x88\x01\x01\x12(\n" +
	"\x10is_paper_trading\x18\x0e \x01(\bR\x0eisPaperTradingB\v\n" +
	"\t_order_idB\r\n" +
	"\v_expired_atB\x0e\n" +
	"\f_strategy_id\"\x9d\b\n" +
	"\x12PlaceOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12+\n" +
	"\x0fclient_order_id\x18\a \x01(\tH\x00R\rclientOrderId\x88\x01\x01\x12\x12\n" +
	"\x04side\x18\b \x01(\tR\x04side\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12\x19\n" +
	"\x05price\x18\n" +
	" \x01(\tH\x01R\x05price\x88\x01\x01\x12\x1a\n" +
	"\bquantity\x18\v \x01(\tR\bquantity\x12'\n" +
	"\x0ffilled_quantity\x18\f \x01(\tR\x0efilledQuantity\x12)\n" +
	"\x0eavg_fill_price\x18\r \x01(\tH\x02R\favgFillPrice\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x1f\n" +
	"\bleverage\x18\x0f \x01(\tH\x03R\bleverage\x88\x01\x01\x12\x15\n" +
	"\x03fee\x18\x10 \x01(\tH\x04R\x03fee\x88\x01\x01\x12&\n" +
	"\frealized_pnl\x18\x11 \x01(\tH\x05R\vrealizedPnl\x88\x01\x01\x123\n" +
	"\x13created_at_exchange\x18\x12 \x01(\x03H\x06R\x11createdAtExchange\x88\x01\x01\x12\x1c\n" +
	"\asent_at\x18\x13 \x01(\x03H\aR\x06sentAt\x88\x01\x01\x12,\n" +
	"\x0facknowledged_at\x18\x14 \x01(\x03H\bR\x0eacknowledgedAt\x88\x01\x01\x12 \n" +
	"\tfilled_at\x18\x15 \x01(\x03H\tR\bfilledAt\x88\x01\x01\x12$\n" +
	"\vstrategy_id\x18\x16 \x01(\tH\n" +
	"R\n" +
	"strategyId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x17 \x01(\tH\vR\ferrorMessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x18 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\x03R\tupdatedAt\x12(\n" +
	"\x10is_paper_trading\x18\x1a \x01(\bR\x0eisPaperTradingB\x12\n" +
	"\x10_client_order_idB\b\n" +
	"\x06_priceB\x11\n" +
	"\x0f_avg_fill_priceB\v\n" +
	"\t_leverageB\x06\n" +
	"\x04_feeB\x0f\n" +
	"\r_realized_pnlB\x16\n" +
	"\x14_created_at_exchangeB\n" +
	"\n" +
	"\b_sent_atB\x12\n" +
	"\x10_acknowledged_atB\f\n" +
	"\n" +
	"_filled_atB\x0e\n" +
	"\f_strategy_idB\x10\n" +
	"\x0e_error_messageB\x11Z\x0fpb/order_engineb\x06proto3"

var (
	file_pb_order_engine_order_proto_rawDescOnce sync.Once
	file_pb_order_engine_order_proto_rawDescData []byte
)

func file_pb_order_engine_order_proto_rawDescGZIP() []byte {
	file_pb_order_engine_order_proto_rawDescOnce.Do(func() {
		file_pb_order_engine_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_order_engine_order_proto_rawDesc), len(file_pb_order_engine_order_proto_rawDesc)))
	})
	return file_pb_order_engine_order_proto_rawDescData
}

var file_pb_order_engine_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_order_engine_order_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),  // 0: pb.order_engine.PlaceOrderRequest
	(*PlaceOrderResponse)(nil), // 1: pb.order_engine.PlaceOrderResponse
}
var file_pb_order_engine_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_order_engine_order_proto_init() }
func file_pb_order_engine_order_proto_init() {
	if File_pb_order_engine_order_proto != nil {
		return
	}
	file_pb_order_engine_order_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_order_engine_order_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_order_engine_order_proto_rawDesc), len(file_pb_order_engine_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_order_engine_order_proto_goTypes,
		DependencyIndexes: file_pb_order_engine_order_proto_depIdxs,
		MessageInfos:      file_pb_order_engine_order_proto_msgTypes,
	}.Build()
	File_pb_order_engine_order_proto = out.File
	file_pb_order_engine_order_proto_goTypes = nil
	file_pb_order_engine_order_proto_depIdxs = nil
}
