import type { ResourceConfig } from "@/types/api";

export const resources: ResourceConfig[] = [
  {
    key: "overview",
    label: "Overview",
    description: "Monitor PnL, open positions, strategy state, order errors, and market-feed freshness.",
    shortDescription: "Bot health and PnL",
    path: "/dashboard",
    idField: "id",
    mode: "readonly",
    readPermission: "order:read",
    columns: [],
    searchableFields: [],
    defaultSort: { field: "exit_time", direction: "desc" },
    navOrder: 0,
  },
  {
    key: "orders",
    label: "Orders & Positions",
    description: "Inspect immutable exchange orders, open positions, execution state, and live PnL.",
    shortDescription: "Execution and positions",
    path: "/orders",
    idField: "id",
    mode: "mutable",
    readPermission: "order:read",
    writePermission: "order:write",
    columns: ["strategy_id", "state", "exchange", "market_type", "symbol", "side", "type", "status", "entry_price", "exit_price", "pnl", "created_at"],
    searchableFields: ["request_id", "symbol", "order_id", "strategy_id"],
    filterFields: ["state", "strategy_id", "symbol", "exchange", "market_type", "status"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      position_side: "position_side",
      side: "order_side",
      type: "order_type",
      status: "order_status",
      state: "order_state",
      trade_condition: "trade_condition",
      exit_type: "exit_type",
    },
    createOnly: true,
    sampleBody: {
      exchange: "binance",
      market_type: "spot",
      position_side: "BOTH",
      symbol: "BTCUSDT",
      side: "BUY",
      quantity: "0.001",
      price: "0",
      need_notification: true,
      is_paper_trading: false,
    },
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Trading",
    navOrder: 10,
  },
  {
    key: "orderPnL",
    label: "Trade History",
    description: "Review closed paired trades with per-trade and running profit or loss.",
    shortDescription: "Closed trades and PnL",
    path: "/order-reports/trades",
    idField: "entry_order_id",
    mode: "readonly",
    readPermission: "order_report:read",
    columns: ["entry_order_id", "strategy_id", "symbol", "side", "entry_price", "exit_price", "qty", "profit", "running_profit", "exit_time"],
    searchableFields: ["entry_order_id", "strategy_id", "symbol"],
    filterFields: ["strategy_id", "symbol"],
    defaultSort: { field: "exit_time", direction: "desc" },
    navParent: "Trading",
    navOrder: 12,
  },
  {
    key: "dailyReports",
    label: "Daily PnL",
    description: "Daily profit and loss grouped by strategy and symbol.",
    shortDescription: "Daily PnL",
    path: "/order-reports/daily",
    idField: "trade_date",
    mode: "readonly",
    readPermission: "order_report:read",
    columns: ["trade_date", "strategy_id", "symbol", "total_profit", "win_rate", "avg_size", "total_trades", "winning_trades", "losing_trades"],
    searchableFields: ["strategy_id", "symbol"],
    filterFields: ["strategy_id", "symbol"],
    defaultSort: { field: "trade_date", direction: "desc" },
    navParent: "Trading",
    navOrder: 14,
  },
  {
    key: "strategyPerformance",
    label: "Strategy Performance",
    description: "Compare strategy-level profitability, win rate, payoff, and trade quality.",
    shortDescription: "Strategy metrics",
    path: "/order-reports/strategy-performance",
    idField: "strategy_id",
    mode: "readonly",
    readPermission: "order_report:read",
    columns: ["strategy_id", "total_profit", "win_rate", "avg_profit", "profit_factor", "total_trades", "winning_trades", "losing_trades", "best_trade", "worst_trade", "last_trade_at"],
    searchableFields: ["strategy_id"],
    filterFields: ["strategy_id", "symbol"],
    defaultSort: { field: "total_profit", direction: "desc" },
    navParent: "Trading",
    navOrder: 16,
  },
  {
    key: "marketKlines",
    label: "Candles",
    description: "Inspect immutable candlestick history consumed by strategies and backfills.",
    shortDescription: "Stored market candles",
    path: "/market/klines",
    idField: "id",
    mode: "readonly",
    readPermission: "market:read",
    columns: ["exchange", "market_type", "symbol", "interval", "open_time", "close_price", "is_closed"],
    searchableFields: ["exchange", "market_type", "symbol", "interval"],
    filterFields: ["symbol", "exchange", "market_type", "interval"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      event_type: "kline_event_type",
      interval: "interval",
    },
    defaultSort: { field: "open_time", direction: "desc" },
    navParent: "Market Data",
    navOrder: 20,
  },
  {
    key: "priceReferences",
    label: "Price Feed",
    description: "Inspect the latest mark price and update time used for open-position PnL.",
    shortDescription: "Latest prices and freshness",
    path: "/market/price-references",
    idField: "id",
    mode: "readonly",
    readPermission: "market:read",
    columns: ["exchange", "market_type", "symbol", "price", "event_time", "updated_at"],
    searchableFields: ["exchange", "market_type", "symbol"],
    filterFields: ["exchange", "market_type", "symbol"],
    enumFields: { exchange: "exchange", market_type: "market_type" },
    defaultSort: { field: "updated_at", direction: "desc" },
    navParent: "Market Data",
    navOrder: 22,
  },
  {
    key: "marketBackfills",
    label: "Backfills",
    description: "Run historical market kline backfills through the market-data gRPC service.",
    shortDescription: "Historical import",
    path: "/market/backfills",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market_config:write",
    columns: ["exchange", "market_type", "symbol", "interval", "status", "inserted_count"],
    searchableFields: ["exchange", "market_type", "symbol", "interval"],
    filterFields: ["exchange", "market_type", "interval"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      interval: "interval",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Market Data",
    navOrder: 25,
  },
  {
    key: "symbolMappings",
    label: "Symbol Mappings",
    description: "Map internal symbols to each exchange's market data and order symbols.",
    path: "/market/symbol-mappings",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market_config:write",
    columns: ["exchange", "market_type", "symbol", "kline_symbol", "order_symbol", "updated_at"],
    searchableFields: ["exchange", "market_type", "symbol", "kline_symbol", "order_symbol"],
    filterFields: ["symbol", "exchange", "market_type"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Market Data",
    navOrder: 30,
    sampleBody: {
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      kline_symbol: "btcusdt",
      order_symbol: "BTCUSDT",
    },
  },
  {
    key: "klineSubscriptions",
    label: "Kline Subscriptions",
    description: "Control subscribed market streams and how much kline history is retained.",
    path: "/market/kline-subscriptions",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market_config:write",
    columns: ["exchange", "market_type", "symbol", "interval", "max_kline_data", "updated_at"],
    searchableFields: ["exchange", "market_type", "symbol", "interval"],
    filterFields: ["symbol", "exchange", "market_type", "interval"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      interval: "interval",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Market Data",
    navOrder: 32,
    sampleBody: {
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      interval: "1m",
      payload: { source: "dashboard" },
      max_kline_data: 1000,
    },
  },
  {
    key: "strategyConfigs",
    label: "Strategies",
    description: "Configure runtime strategy behavior, order sizing, and risk controls.",
    path: "/strategy/configs",
    idField: "id",
    mode: "mutable",
    readPermission: "strategy_config:read",
    writePermission: "strategy_config:write",
    columns: ["strategy", "enabled", "exchange", "market_type", "symbol", "interval", "source", "updated_at"],
    searchableFields: ["strategy", "exchange", "market_type", "symbol", "interval", "user_id", "source"],
    filterFields: ["enabled", "symbol", "exchange", "market_type", "interval", "source"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      interval: "interval",
      position_side: "position_side",
      source: "source",
      enabled: "boolean",
      order_type: "order_type",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Automation",
    navOrder: 18,
    sampleBody: {
      strategy: "python-krobot01-ema200-vwap-macd",
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      interval: "1m",
      user_id: "minimax-01",
      position_side: "BOTH",
      source: "dashboard",
      enabled: true,
      need_notification: true,
      is_paper_trading: true,
      order_type: "MARKET",
      order_qty: "10",
      limit_slippage_pct: "0.02",
      cooldown_bars: 2,
      sl_cooldown_bars: 3,
      max_consecutive_stop_losses: 2,
      sl_pause_bars: 10,
      take_profit_pct: "0.25",
      stop_loss_pct: "0.15",
      trailing_stop_pct: "0.12",
      trailing_stop_trigger_pct: "0.20",
      max_hold_bars: 24,
      max_positions: 1,
      enable_intrabar_risk_exit: true,
    },
  },
  {
    key: "settings",
    label: "Settings",
    description: "Manage dashboard settings and feature flags for the API service.",
    path: "/settings",
    idField: "id",
    mode: "mutable",
    readPermission: "settings:read",
    writePermission: "settings:write",
    columns: ["key", "value", "updated_at"],
    searchableFields: ["key"],
    defaultSort: { field: "updated_at", direction: "desc" },
    navParent: "Administration",
    navOrder: 90,
    sampleBody: {
      key: "dashboard.show_setup_link",
      value: "true",
    },
  },
  {
    key: "users",
    label: "Users",
    description: "Manage dashboard user access and account status.",
    path: "/users",
    idField: "id",
    mode: "mutable",
    readPermission: "user:read",
    writePermission: "user:write",
    columns: ["email", "name", "active", "last_login_at", "created_at"],
    searchableFields: ["email", "name"],
    defaultSort: { field: "created_at", direction: "desc" },
    navParent: "Administration",
    navOrder: 70,
    sampleBody: {
      email: "viewer@example.com",
      name: "Viewer",
      password: "",
      active: true,
      roles: "viewer",
    },
    enumFields: {
      roles: "role",
    },
    multiEnumFields: ["roles"],
  },
  {
    key: "roles",
    label: "Roles",
    description: "Manage role-based access groups and their permission assignments.",
    path: "/roles",
    idField: "id",
    mode: "mutable",
    readPermission: "user:read",
    writePermission: "user:write",
    columns: ["name", "description", "created_at"],
    searchableFields: ["name", "description"],
    defaultSort: { field: "name", direction: "asc" },
    navParent: "Administration",
    navOrder: 72,
    sampleBody: {
      name: "operator",
      description: "Operational dashboard access",
      permissions: "order:read,market:read,strategy_config:read,settings:read",
    },
    enumFields: {
      permissions: "permission",
    },
    multiEnumFields: ["permissions"],
  },
  {
    key: "permissions",
    label: "Permissions",
    description: "Manage API permission names and descriptions used by roles and page rules.",
    path: "/permissions",
    idField: "id",
    mode: "mutable",
    readPermission: "permission:read",
    writePermission: "permission:write",
    columns: ["name", "description", "created_at"],
    searchableFields: ["name", "description"],
    defaultSort: { field: "name", direction: "asc" },
    navParent: "Administration",
    navOrder: 74,
    sampleBody: {
      name: "feature:read",
      description: "Read feature data",
    },
  },
  {
    key: "dashboardPages",
    label: "Navigation",
    description: "Manage sidebar labels, grouping, ordering, visibility, and permission overrides.",
    path: "/dashboard/pages",
    idField: "id",
    mode: "mutable",
    readPermission: "dashboard_page:read",
    writePermission: "dashboard_page:write",
    columns: ["sort_order", "parent_key", "label", "resource_key", "read_permission", "write_permission", "visible"],
    searchableFields: ["resource_key", "parent_key", "label", "description", "path", "read_permission", "write_permission"],
    filterFields: ["parent_key", "resource_key", "read_permission"],
    enumFields: {
      resource_key: "dashboard_page",
      read_permission: "permission",
      write_permission: "permission",
    },
    defaultSort: { field: "sort_order", direction: "asc" },
    navParent: "Administration",
    navOrder: 92,
    sampleBody: {
      resource_key: "orders",
      parent_key: "Trading",
      label: "Orders & Positions",
      description: "Inspect immutable exchange orders, open positions, execution state, and live PnL.",
      short_description: "Execution and positions",
      icon: "activity",
      path: "/dashboard/orders",
      read_permission: "order:read",
      write_permission: "",
      sort_order: 10,
      visible: true,
    },
  },
];
