import type { ResourceConfig } from "@/types/api";

export const resources: ResourceConfig[] = [
  {
    key: "orders",
    label: "Orders",
    description: "Review and maintain trading order records from the order engine.",
    path: "/orders",
    idField: "id",
    mode: "mutable",
    readPermission: "order:read",
    writePermission: "order:write",
    columns: ["exchange", "market_type", "symbol", "side", "type", "status", "created_at"],
    searchableFields: ["request_id", "symbol", "order_id", "strategy_id"],
    filterFields: ["symbol", "exchange", "market_type"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      position_side: "position_side",
      side: "order_side",
      type: "order_type",
      status: "order_status",
      trade_condition: "trade_condition",
      exit_type: "exit_type",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    sampleBody: {
      request_id: "dashboard-request-01",
      user_id: "dashboard",
      exchange: "binance",
      market_type: "futures",
      position_side: "BOTH",
      symbol: "BTC_USDT",
      order_id: "exchange-order-01",
      entry_order_id: "",
      client_order_id: "",
      side: "BUY",
      type: "MARKET",
      price: "",
      quantity: "1",
      filled_quantity: "0",
      avg_fill_price: "",
      status: "NEW",
      leverage: "",
      fee: "",
      realized_pnl: "",
      created_at_exchange: "",
      sent_at: "",
      acknowledged_at: "",
      filled_at: "",
      strategy_id: "",
      trade_condition: "UNKNOWN",
      order_reason: "",
      exit_type: "",
      error_message: "",
      is_paper_trading: true,
    },
  },
  {
    key: "marketKlines",
    label: "Market Klines",
    description: "Inspect and manage stored candlestick data used by strategies and backfills.",
    path: "/market/klines",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market:write",
    columns: ["exchange", "market_type", "symbol", "interval", "open_time", "close_price", "is_closed"],
    searchableFields: ["exchange", "market_type", "symbol", "interval"],
    filterFields: ["symbol", "exchange", "market_type", "interval"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      event_type: "kline_event_type",
      interval: "interval",
    },
    defaultSort: { field: "open_time", direction: "desc" },
    sampleBody: {
      exchange: "binance",
      market_type: "futures",
      event_type: "kline",
      event_time: new Date().toISOString(),
      symbol: "BTC_USDT",
      interval: "1m",
      open_time: new Date().toISOString(),
      close_time: new Date().toISOString(),
      open_price: "0",
      high_price: "0",
      low_price: "0",
      close_price: "0",
      base_volume: "0",
      quote_volume: "0",
      taker_base_volume: "0",
      taker_quote_volume: "0",
      trade_count: 0,
      is_closed: false,
    },
  },
  {
    key: "symbolMappings",
    label: "Symbol Mappings",
    description: "Map internal symbols to each exchange's market data and order symbols.",
    path: "/market/symbol-mappings",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market_config:write",
    columns: ["exchange", "market_type", "symbol", "kline_symbol", "order_symbol", "updated_at"],
    searchableFields: ["exchange", "market_type", "symbol", "kline_symbol", "order_symbol"],
    filterFields: ["symbol", "exchange", "market_type"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    sampleBody: {
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      kline_symbol: "btcusdt",
      order_symbol: "BTCUSDT",
    },
  },
  {
    key: "klineSubscriptions",
    label: "Kline Subscriptions",
    description: "Control subscribed market streams and how much kline history is retained.",
    path: "/market/kline-subscriptions",
    idField: "id",
    mode: "mutable",
    readPermission: "market:read",
    writePermission: "market_config:write",
    columns: ["exchange", "market_type", "symbol", "interval", "max_kline_data", "updated_at"],
    searchableFields: ["exchange", "market_type", "symbol", "interval"],
    filterFields: ["symbol", "exchange", "market_type", "interval"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      interval: "interval",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    sampleBody: {
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      interval: "1m",
      payload: { source: "dashboard" },
      max_kline_data: 1000,
    },
  },
  {
    key: "strategyConfigs",
    label: "Strategy Configs",
    description: "Configure runtime strategy behavior, order sizing, and risk controls.",
    path: "/strategy/configs",
    idField: "id",
    mode: "mutable",
    readPermission: "strategy_config:read",
    writePermission: "strategy_config:write",
    columns: ["strategy", "exchange", "market_type", "symbol", "interval", "source", "updated_at"],
    searchableFields: ["strategy", "exchange", "market_type", "symbol", "interval", "user_id", "source"],
    filterFields: ["symbol", "exchange", "market_type", "interval", "source"],
    enumFields: {
      exchange: "exchange",
      market_type: "market_type",
      interval: "interval",
      position_side: "position_side",
      source: "source",
      order_type: "order_type",
    },
    defaultSort: { field: "created_at", direction: "desc" },
    sampleBody: {
      strategy: "python-krobot01-ema200-vwap-macd",
      exchange: "binance",
      market_type: "futures",
      symbol: "BTC_USDT",
      interval: "1m",
      user_id: "minimax-01",
      position_side: "BOTH",
      source: "dashboard",
      need_notification: true,
      is_paper_trading: true,
      order_type: "MARKET",
      order_qty: "10",
      limit_slippage_pct: "0.02",
      cooldown_bars: 2,
      sl_cooldown_bars: 3,
      max_consecutive_stop_losses: 2,
      sl_pause_bars: 10,
      take_profit_pct: "0.25",
      stop_loss_pct: "0.15",
      trailing_stop_pct: "0.12",
      trailing_stop_trigger_pct: "0.20",
      max_hold_bars: 24,
      max_positions: 1,
      enable_intrabar_risk_exit: true,
    },
  },
  {
    key: "settings",
    label: "Settings",
    description: "Manage dashboard settings and feature flags for the API service.",
    path: "/settings",
    idField: "id",
    mode: "mutable",
    readPermission: "settings:read",
    writePermission: "settings:write",
    columns: ["key", "value", "updated_at"],
    searchableFields: ["key"],
    defaultSort: { field: "updated_at", direction: "desc" },
    sampleBody: {
      key: "dashboard.show_setup_link",
      value: "true",
    },
  },
  {
    key: "users",
    label: "Users",
    description: "Manage dashboard user access and account status.",
    path: "/users",
    idField: "id",
    mode: "mutable",
    readPermission: "user:read",
    writePermission: "user:write",
    columns: ["email", "name", "active", "last_login_at", "created_at"],
    searchableFields: ["email", "name"],
    defaultSort: { field: "created_at", direction: "desc" },
    sampleBody: {
      email: "viewer@example.com",
      name: "Viewer",
      password: "",
      active: true,
      roles: "viewer",
    },
    enumFields: {
      roles: "role",
    },
    multiEnumFields: ["roles"],
  },
  {
    key: "roles",
    label: "Roles",
    description: "Manage role-based access groups and their permission assignments.",
    path: "/roles",
    idField: "id",
    mode: "mutable",
    readPermission: "user:read",
    writePermission: "user:write",
    columns: ["name", "description", "created_at"],
    searchableFields: ["name", "description"],
    defaultSort: { field: "name", direction: "asc" },
    sampleBody: {
      name: "operator",
      description: "Operational dashboard access",
      permissions: "order:read,market:read,strategy_config:read,settings:read",
    },
    enumFields: {
      permissions: "permission",
    },
    multiEnumFields: ["permissions"],
  },
  {
    key: "permissions",
    label: "Permissions",
    description: "Manage API permission names and descriptions used by roles and page rules.",
    path: "/permissions",
    idField: "id",
    mode: "mutable",
    readPermission: "permission:read",
    writePermission: "permission:write",
    columns: ["name", "description", "created_at"],
    searchableFields: ["name", "description"],
    defaultSort: { field: "name", direction: "asc" },
    sampleBody: {
      name: "feature:read",
      description: "Read feature data",
    },
  },
  {
    key: "dashboardPages",
    label: "Dashboard Pages",
    description: "Manage sidebar pages, submenu grouping, ordering, visibility, and permission overrides.",
    path: "/dashboard/pages",
    idField: "id",
    mode: "mutable",
    readPermission: "dashboard_page:read",
    writePermission: "dashboard_page:write",
    columns: ["sort_order", "parent_key", "label", "resource_key", "read_permission", "write_permission", "visible"],
    searchableFields: ["resource_key", "parent_key", "label", "description", "path", "read_permission", "write_permission"],
    filterFields: ["parent_key", "resource_key", "read_permission"],
    enumFields: {
      resource_key: "dashboard_page",
      read_permission: "permission",
      write_permission: "permission",
    },
    defaultSort: { field: "sort_order", direction: "asc" },
    sampleBody: {
      resource_key: "orders",
      parent_key: "Trading",
      label: "Orders",
      description: "Review and maintain trading order records from the order engine.",
      short_description: "Order records",
      icon: "activity",
      path: "/dashboard/orders",
      read_permission: "order:read",
      write_permission: "order:write",
      sort_order: 10,
      visible: true,
    },
  },
];

export function firstReadableResource(readableKeys: Set<string>) {
  return resources.find((resource) => readableKeys.has(resource.key));
}
