// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/market_data/market_data.proto

package market_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackfillMarketKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MarketType    string                 `protobuf:"bytes,6,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillMarketKlinesRequest) Reset() {
	*x = BackfillMarketKlinesRequest{}
	mi := &file_pb_market_data_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillMarketKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillMarketKlinesRequest) ProtoMessage() {}

func (x *BackfillMarketKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_market_data_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillMarketKlinesRequest.ProtoReflect.Descriptor instead.
func (*BackfillMarketKlinesRequest) Descriptor() ([]byte, []int) {
	return file_pb_market_data_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *BackfillMarketKlinesRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *BackfillMarketKlinesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BackfillMarketKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *BackfillMarketKlinesRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BackfillMarketKlinesRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BackfillMarketKlinesRequest) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

type BackfillMarketKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount int64                  `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillMarketKlinesResponse) Reset() {
	*x = BackfillMarketKlinesResponse{}
	mi := &file_pb_market_data_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillMarketKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillMarketKlinesResponse) ProtoMessage() {}

func (x *BackfillMarketKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_market_data_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillMarketKlinesResponse.ProtoReflect.Descriptor instead.
func (*BackfillMarketKlinesResponse) Descriptor() ([]byte, []int) {
	return file_pb_market_data_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *BackfillMarketKlinesResponse) GetInsertedCount() int64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

var File_pb_market_data_market_data_proto protoreflect.FileDescriptor

const file_pb_market_data_market_data_proto_rawDesc = "" +
	"\n" +
	" pb/market_data/market_data.proto\x12\x0epb.market_data\"\xc8\x01\n" +
	"\x1bBackfillMarketKlinesRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vmarket_type\x18\x06 \x01(\tR\n" +
	"marketType\"E\n" +
	"\x1cBackfillMarketKlinesResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x03R\rinsertedCount2\x86\x01\n" +
	"\x11MarketDataService\x12q\n" +
	"\x14BackfillMarketKlines\x12+.pb.market_data.BackfillMarketKlinesRequest\x1a,.pb.market_data.BackfillMarketKlinesResponseB\x10Z\x0epb/market_datab\x06proto3"

var (
	file_pb_market_data_market_data_proto_rawDescOnce sync.Once
	file_pb_market_data_market_data_proto_rawDescData []byte
)

func file_pb_market_data_market_data_proto_rawDescGZIP() []byte {
	file_pb_market_data_market_data_proto_rawDescOnce.Do(func() {
		file_pb_market_data_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_market_data_market_data_proto_rawDesc), len(file_pb_market_data_market_data_proto_rawDesc)))
	})
	return file_pb_market_data_market_data_proto_rawDescData
}

var file_pb_market_data_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_market_data_market_data_proto_goTypes = []any{
	(*BackfillMarketKlinesRequest)(nil),  // 0: pb.market_data.BackfillMarketKlinesRequest
	(*BackfillMarketKlinesResponse)(nil), // 1: pb.market_data.BackfillMarketKlinesResponse
}
var file_pb_market_data_market_data_proto_depIdxs = []int32{
	0, // 0: pb.market_data.MarketDataService.BackfillMarketKlines:input_type -> pb.market_data.BackfillMarketKlinesRequest
	1, // 1: pb.market_data.MarketDataService.BackfillMarketKlines:output_type -> pb.market_data.BackfillMarketKlinesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_market_data_market_data_proto_init() }
func file_pb_market_data_market_data_proto_init() {
	if File_pb_market_data_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_market_data_market_data_proto_rawDesc), len(file_pb_market_data_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_market_data_market_data_proto_goTypes,
		DependencyIndexes: file_pb_market_data_market_data_proto_depIdxs,
		MessageInfos:      file_pb_market_data_market_data_proto_msgTypes,
	}.Build()
	File_pb_market_data_market_data_proto = out.File
	file_pb_market_data_market_data_proto_goTypes = nil
	file_pb_market_data_market_data_proto_depIdxs = nil
}
